version: "2"
services:
  elasticsearch:
    image: elasticsearch:5.6.11
    command: elasticsearch -Des.network.host=127.0.0.1
  kibana:
    image: kibana:5.6.11
    ports:
      - "5601:80"
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:5.6.11
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash:/etc/logstash/conf.d
      - ./logstash/patterns:/opt/logstash/patterns
    depends_on:
      - elasticsearch
  filebeat:
    image: prima/filebeat
    volumes:
      - ./filebeat/filebeat.yml:/filebeat.yml
      - ../fake-logs:/var/log
    depends_on:
      - logstash
